name: Tests

on:
  push:
    branches: [ main, 1.x ]
  pull_request:
    branches: [ main, 1.x ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, curl, libxml, zip
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer self-update
          composer install --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit